package com.fastcampus.kafkahandson.ugc.postsearch;

import com.fastcampus.kafkahandson.ugc.inspectedpost.InspectedPost;
import com.fastcampus.kafkahandson.ugc.port.PostSearchPort;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;

@Component
@RequiredArgsConstructor
public class PostSearchAdapter implements PostSearchPort {

    private final PostSearchRepository postSearchRepository;

    @Override
    public void indexPost(InspectedPost post) {
        postSearchRepository.save(toDocument(post));
    }

    @Override
    public void deletePost(Long id) {
        postSearchRepository.deleteById(id);
    }

    public static PostDocument toDocument(InspectedPost post) {
        return new PostDocument(
                post.getPost().getId(),
                post.getPost().getTitle(),
                post.getPost().getContent(),
                post.getCategoryName(),
                post.getAutoGeneratedTags(),
                LocalDateTime.now()
        );
    }
}
